Feature/732 Datepicker
Gepardec/mega-frontend-app pull request #4
Opened 2024-01-18 07:48 UTC by LeitnerMi

**Prerequisites: Always create two feature branches (frontend + backend) even if your feature only affects one of them**

**DEV:**
> Development
- [ ] Acceptance tests by dev [OpenShift feature environment]
  - [ ] Moved to "Ready for review"

> Review
- [ ] Pull-request reviewed + approved (including Code Coverage) by reviewer [GitHub]
- [ ] Inform dev after review through MEGA-PR (by reviewer) [Chat Space]
- [ ] Version upgrade by dev [GitHub Issue Milestone + maven revision]
- [ ] Merge to main by dev [GitHub]
  - [ ] Moved to "Ready for deployment"

> Deployment
- [ ] Integration and Unit tests on main environment passed [Workflow]
- [ ] Deployed to the test environment [GitOps Workflow triggered]
  - [ ] Moved to "Ready for testing"

**PO:**
> Testing
- [ ] Acceptance tests on the test enviroment passed
- [ ] Inspected and approved
  - [ ] Moved to "Ready for release"

2024-01-18 09:10 UTC, Ruhsi requested changes

2024-01-18 09:10 UTC, Ruhsi commented on libs/shared/ui/src/lib/date-picker-custom-header/date-picker-custom-header.component.spec.ts
> +  let component: DatePickerCustomHeaderComponent;
I think you need the generics here as well:
DatePickerCustomHeaderComponent<any>

2024-01-18 09:10 UTC, Ruhsi commented on libs/shared/ui/src/lib/date-picker-custom-header/date-picker-custom-header.component.spec.ts
> +  let fixture: ComponentFixture<DatePickerCustomHeaderComponent>;
and here: 
let fixture: ComponentFixture<DatePickerCustomHeaderComponent<any>>

2024-01-18 09:10 UTC, Ruhsi commented on libs/shared/ui/src/lib/date-picker-custom-header/date-picker-custom-header.component.spec.ts
> +    fixture = TestBed.createComponent(DatePickerCustomHeaderComponent);
fixture = TestBed.createComponent(DatePickerCustomHeaderComponent<any>);

2024-01-18 09:10 UTC, Ruhsi commented on libs/shared/ui/src/lib/datepicker-month-year/datepicker-month-year.component.ts
> +  dateFormControl = new FormControl(this.date);
don't know the conventions but some with type some without?

2024-01-19 06:12 UTC, Ollitod commented
1. DatePickerCustomHeaderComponent should be moved to the directory of DatepickerMonthYearComponent as a subdirectory.

2024-01-19 14:08 UTC, merged